In [27]:
import pandas as pd

interest_rate_file = 'data/interestrate.csv'
exchange_rate_file = 'data/exchange_rate.csv'

interest = pd.read_csv(interest_rate_file, header=0).dropna()
exchange = pd.read_csv(exchange_rate_file, header=0).dropna()

### Drop rows from 0 to 6 ###
interest = interest.drop([0,1,2,3,4,5,6])
def map_date_for_exchange(string):
    splits = string.split('/')
    year = int(splits[2])

    if(year <= 20):
        year = '20' + '{:02d}'.format(year)
    else:
        year = '19' + str(year)
        
    return year

exchange['date'] = exchange['date'].apply(map_date_for_exchange)
exchange = exchange.groupby('date').mean()

In [28]:

def map_date_for_interest(string):
    splits = string.split(' ')
    year = splits[0]
    
    return year

interest['Series Name'] = interest['Series Name'].apply(map_date_for_interest)
interest = interest.rename(columns={'Series Name' : 'year'})
exchange.index.names = ['year']
exchange = exchange.rename(columns={'value':'exchange_rate'})
print(interest)
print(exchange)

   Real interest rate (%)  year  Real interest rate (%).1
7             3.006699115  1978                  1.889901
8             3.105095836  1979                  4.034513
9             0.534883963  1980                  5.716428
10            7.338554178  1981                  8.594585
11            5.448374541  1982                  8.177395
12            5.698778458  1983                  6.618174
13             8.86152616  1984                  8.141075
14            9.671217946  1985                  6.563326
15            8.175299093  1986                  6.193866
16            5.537930896  1987                  5.592565
17             0.50611088  1988                  5.590367
18            1.970336056  1989                  6.690695
19            2.545643279  1990                  6.039744
20            3.014395146  1991                  4.915352
21             4.50220448  1992                  3.884240
22            1.870453883  1993                  3.546689
23            2.336551651  1994                  4.898356
24            3.119130585  1995                  6.594069
25            4.683226223  1996                  6.324008
26            5.184891291  1997                  6.603407
27            8.883774641  1998                  7.148192
28             9.73165276  1999                  6.457135
29            1.897357839  2000                  6.844844
30            7.602682858  2001                  4.626757
31            6.290296818  2002                  3.045071
32            7.223096294  2003                  2.224101
33            1.178498844  2004                  1.604589
34            3.329063438  2005                  2.981357
35            3.403974107  2006                  4.786448
36           -0.553483124  2007                  5.223406
37            6.861274214  2008                  3.082411
38             2.34934131  2009                  2.468829
39            4.230742021  2010                  2.060737
40             4.28104961  2011                  1.137338
41            4.886795201  2012                  1.307083
42            5.856075732  2013                  1.469299
43            5.634826207  2014                  1.332892
44            2.221784267  2015                  2.167481
45            4.622535915  2016                  2.391984
46            2.432034112  2017                  2.154929
47            2.173523082  2018                  2.485817
48             5.15024813  2019                  3.478200
      exchange_rate
year
1991       1.725803
1992       1.627552
1993       1.614162
1994       1.526160
1995       1.416476
1996       1.409301
1997       1.485083
1998       1.670541
1999       1.694099
2000       1.724370
2001       1.792048
2002       1.789727
2003       1.741523
2004       1.689433
2005       1.663994
2006       1.588212
2007       1.506286
2008       1.414039
2009       1.453315
2010       1.361839
2011       1.256763
2012       1.248700
2013       1.250721
2014       1.266712
2015       1.375154
2016       1.380730
2017       1.380627
2018       1.349247
2019       1.364148
2020       1.385685

In [29]:
interest['Real interest rate (%)'] = interest['Real interest rate (%)'].astype('float')
merged = pd.merge(interest, exchange, on='year')
merged.corr()

,Real interest rate (%),Real interest rate (%).1,exchange_rate
Real interest rate (%),1.000000,0.135053,0.157648
Real interest rate (%).1,0.135053,1.000000,0.460685
exchange_rate,0.157648,0.460685,1.000000

In [30]:
merged.to_csv('data/interest_and_exchange.csv')